settings:
  #Available log levels so far, Everything 1, Normal 3, Critical 5
  log-level: 3
  max-score-limit: 15
  default-set: 'Base Set'
  idle-timer:
    maximum: 600
    default: 60
    minimum: 10
  #May seriously bug out if set over 7
  player-count:
    maximum: 7
    minimum: 3
    
#Do not change this!
config-version: 1
